### ISSUE TITLE
App Crash on library initialisation

### ISSUE THREAD

**Issue by fazzee** [matinzd/react-native-health-connect#178] opened 2024-11-21 16:00 UTC
**App Crash on library initialisation**
My App is crashed on initialisation of the library, and I'm getting these errors. I've completed all the configurations as described in Docs.

**Screenshots**  
![Screenshot 2024-11-21 at 10 42 46 AM](https://github.com/user-attachments/assets/d0daf969-c8f4-4f8c-b966-710f2a24e087)
![image](https://github.com/user-attachments/assets/27824e47-d776-4de3-bd83-547b4511c316)

**Minimal Reproducible**  
Link to minimal reproducible code. It would be much easier for us to investigate the issue!

**Environment:**
 - Health Connect Version: "^3.1.0"
 - React Native Version: "0.74.5"
 - New architecture enabled: Yes
 - Using Expo: Prebuild(Dev Client)
 - Android API Level: e.g API 34 (Android 14)

**Comment by matinzd** [comment] 2024-11-23 16:35
There have been some breaking changes in the v3.3.0:

https://github.com/matinzd/react-native-health-connect/releases/tag/v3.3.0

If that didn't help can you create a minimal reproducible and share it with me? Thanks

**Comment by matinzd** [comment] 2024-12-23 14:11
Closing this as I could not reproduce it and didn't get any answers.

**Closed** 2024-12-23 14:11 UTC
Labels: Type: bug
