### ISSUE TITLE
Can't get past requestPermission

### ISSUE THREAD

**Issue by BlocknBoom123** [matinzd/react-native-health-connect#137] opened 2024-08-20 07:15 UTC
My program keeps getting stuck on requestPermission as the promise never resolves. It never returns the grantedPermissions object and it remains empty. I get the dialogue box to allow access to health connect but when I click steps/distance and click allow, I get back to my main screen and no state is updated, as hitting allow doesn't finish that requestPermission method. It will never reach that console.log('hello) step or write to my state field, and as such androidPermissions remains empty. I'm not using expo.
    

    console.log('1');
    const grantedPermissions = await requestPermission([
      { accessType: 'read', recordType: 'Steps' },
      { accessType: 'read', recordType: 'Distance' },
    ]);
    console.log('hello')
    setAndroidPermissions(grantedPermissions);

![image](https://github.com/user-attachments/assets/c89fcfad-8567-45a0-9c8a-9d3857ff6ce9)

**Comment by matinzd** [comment] 2024-08-20 08:54
Did you follow the document to setup your Android project in the native code?

https://matinzd.github.io/react-native-health-connect/docs/get-started

**Comment by BlocknBoom123** [comment] 2024-08-20 09:24
Yes I did. I do get permissions but await requestPermission() will never finish running and return the granted permissions. I have to run requestPermissions twice to see the updated permissions using getGrantedPermissions.

Also, how do we link/grab the steps or distance for each exercise session? I can read the cycling, walking, or running sessions I've done but I can't get their respective distances. How do I get that?

Lastly, do you know how distance is actually recorded? Because I see loads of distance records that last around 2 ms each, instead of entire walking sessions around 30 minutes.

**Comment by matinzd** [comment] 2024-08-21 10:00
Please open another issue for the second question. For the permission issue please send me a reproduction so I can find what's going on. Thanks!

**Comment by matinzd** [comment] 2024-08-21 10:07
Also try to always fill in the bug report template for other repositories as well. Removing the template and not providing any debug/version information will reduce the possibility of fixing the issue. 

Thanks for your collaboration.

**Comment by heritvithalani19** [comment] 2024-09-03 05:45
I faced the same issue.requestPermission as the promise never resolves

**Comment by heritvithalani19** [comment] 2024-09-04 03:59
@BlocknBoom123 


> Yes I did. I do get permissions but await requestPermission() will never finish running and return the granted permissions. I have to run requestPermissions twice to see the updated permissions using getGrantedPermissions.
> 
> Also, how do we link/grab the steps or distance for each exercise session? I can read the cycling, walking, or running sessions I've done but I can't get their respective distances. How do I get that?
> 
> Lastly, do you know how distance is actually recorded? Because I see loads of distance records that last around 2 ms each, instead of entire walking sessions around 30 minutes.

Has there been any progress on finding a solution to this issue?

**Comment by matinzd** [comment] 2024-09-04 06:58
Duplicate of https://github.com/matinzd/react-native-health-connect/issues/147.

Closing.

**Closed by matinzd** 2024-09-04 06:58 UTC
Labels: Type: bug
